global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector-metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']

