global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
